# Generated by Django 3.1.7 on 2021-02-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(default='math', max_length=1, on_delete=django.db.models.deletion.CASCADE, to='student.faculty'),
        ),
    ]
